/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AnalyzeIndexRouteImport } from './routes/analyze/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as CandidatesIndexRouteImport } from './routes/candidates/index'
import { Route as CandidatesSlugRouteImport } from './routes/candidates/$slug'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as ReportsIdRouteImport } from './routes/reports/$id'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SyncIndexRouteImport } from './routes/sync/index'
import { Route as ApiGmailCallbackRouteImport } from './routes/api/gmail/callback'
import { Route as PdfProxySlugFilenameRouteImport } from './routes/pdf-proxy/$slug/$filename'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeIndexRoute = AnalyzeIndexRouteImport.update({
  id: '/analyze/',
  path: '/analyze/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesSlugRoute = CandidatesSlugRouteImport.update({
  id: '/candidates/$slug',
  path: '/candidates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncIndexRoute = SyncIndexRouteImport.update({
  id: '/sync/',
  path: '/sync/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailCallbackRoute = ApiGmailCallbackRouteImport.update({
  id: '/api/gmail/callback',
  path: '/api/gmail/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfProxySlugFilenameRoute = PdfProxySlugFilenameRouteImport.update({
  id: '/pdf-proxy/$slug/$filename',
  path: '/pdf-proxy/$slug/$filename',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/candidates/$slug': typeof CandidatesSlugRoute
  '/reports/$id': typeof ReportsIdRoute
  '/analyze/': typeof AnalyzeIndexRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sync/': typeof SyncIndexRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/pdf-proxy/$slug/$filename': typeof PdfProxySlugFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/candidates/$slug': typeof CandidatesSlugRoute
  '/reports/$id': typeof ReportsIdRoute
  '/analyze': typeof AnalyzeIndexRoute
  '/candidates': typeof CandidatesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sync': typeof SyncIndexRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/pdf-proxy/$slug/$filename': typeof PdfProxySlugFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/candidates/$slug': typeof CandidatesSlugRoute
  '/reports/$id': typeof ReportsIdRoute
  '/analyze/': typeof AnalyzeIndexRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sync/': typeof SyncIndexRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/pdf-proxy/$slug/$filename': typeof PdfProxySlugFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/candidates/$slug'
    | '/reports/$id'
    | '/analyze/'
    | '/candidates/'
    | '/reports/'
    | '/settings/'
    | '/sync/'
    | '/api/gmail/callback'
    | '/pdf-proxy/$slug/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/candidates/$slug'
    | '/reports/$id'
    | '/analyze'
    | '/candidates'
    | '/reports'
    | '/settings'
    | '/sync'
    | '/api/gmail/callback'
    | '/pdf-proxy/$slug/$filename'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/candidates/$slug'
    | '/reports/$id'
    | '/analyze/'
    | '/candidates/'
    | '/reports/'
    | '/settings/'
    | '/sync/'
    | '/api/gmail/callback'
    | '/pdf-proxy/$slug/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CandidatesSlugRoute: typeof CandidatesSlugRoute
  ReportsIdRoute: typeof ReportsIdRoute
  AnalyzeIndexRoute: typeof AnalyzeIndexRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SyncIndexRoute: typeof SyncIndexRoute
  ApiGmailCallbackRoute: typeof ApiGmailCallbackRoute
  PdfProxySlugFilenameRoute: typeof PdfProxySlugFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/': {
      id: '/analyze/'
      path: '/analyze'
      fullPath: '/analyze/'
      preLoaderRoute: typeof AnalyzeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$slug': {
      id: '/candidates/$slug'
      path: '/candidates/$slug'
      fullPath: '/candidates/$slug'
      preLoaderRoute: typeof CandidatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync/': {
      id: '/sync/'
      path: '/sync'
      fullPath: '/sync/'
      preLoaderRoute: typeof SyncIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail/callback': {
      id: '/api/gmail/callback'
      path: '/api/gmail/callback'
      fullPath: '/api/gmail/callback'
      preLoaderRoute: typeof ApiGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-proxy/$slug/$filename': {
      id: '/pdf-proxy/$slug/$filename'
      path: '/pdf-proxy/$slug/$filename'
      fullPath: '/pdf-proxy/$slug/$filename'
      preLoaderRoute: typeof PdfProxySlugFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CandidatesSlugRoute: CandidatesSlugRoute,
  ReportsIdRoute: ReportsIdRoute,
  AnalyzeIndexRoute: AnalyzeIndexRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SyncIndexRoute: SyncIndexRoute,
  ApiGmailCallbackRoute: ApiGmailCallbackRoute,
  PdfProxySlugFilenameRoute: PdfProxySlugFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
